# Generated by Django 5.0.3 on 2025-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
